### ISSUE TITLE
Feat: Add Google analytics(on-hold))

### ISSUE THREAD

**Issue by nitaxmx** [Bloinx/bloinx-v2#14]
Source, geografic areas and time.

**Comment by justwheel** [comment]
I wanted to point out a risk for consideration about Google Analytics. Recently in the UNICEF Venture Fund mentor team, we were monitoring the recent illegalization of Google Analytics in [Austria](https://noyb.eu/en/austrian-dsb-eu-us-data-transfers-google-analytics-illegal), [France](https://www.cnil.fr/en/use-google-analytics-and-data-transfers-united-states-cnil-orders-website-manageroperator-comply), and [Italy](https://www.gpdp.it/web/guest/home/docweb/-/docweb-display/docweb/9782874). While these cases are within European law, it sets a precedent about data sovereignty and how different nations can have different levels of protection for their citizens regarding data, where it is stored, and how it can be processed.

_Opensource.com_ publishes a helpful article to explore alternatives to this topic, similar to the Google Firebase to Supabase exploration: [**Top 5 open source alternatives to Google Analytics**](https://opensource.com/article/18/1/top-5-open-source-analytics-tools)
